[project]
name = "cc-map"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cartopy>=0.25.0",
    "geopy>=2.4.1",
    "matplotlib>=3.10.5",
    "pandas>=2.3.1",
]
